from model.backbone.resnet18_student import resnet18_student
from model.backbone.resnet50_student import resnet50_stduent
from model.backbone.extract_feature_backbone import resnet50_extract
from model.backbone.strm18_student import strm18_student
from model.backbone.meta_baseline import meta_baseline
from model.backbone.meta_baseline_fc2 import meta_baseline_fc2